// This is a generated file. The source files are in react-dom-bindings/src/server/fizz-instruction-set.
// The build script is at scripts/rollup/generate-inline-fizz-runtime.js.
// Run `yarn generate-inline-fizz-runtime` to generate.
export const markShellTime =
  'requestAnimationFrame(function(){$RT=performance.now()});';
export const clientRenderBoundary =
  '$RX=function(b,c,d,e,f){var a=document.getElementById(b);a&&(b=a.previousSibling,b.data="$!",a=a.dataset,null!=c&&(a.dgst=c),d&&(a.msg=d),e&&(a.stck=e),f&&(a.cstck=f),b._reactRetry&&b._reactRetry())};';
export const completeBoundary =
  '$RB=[];$RV=function(a){$RT=performance.now();for(var b=0;b<a.length;b+=2){var c=a[b],e=a[b+1];null!==e.parentNode&&e.parentNode.removeChild(e);var f=c.parentNode;if(f){var g=c.previousSibling,h=0;do{if(c&&8===c.nodeType){var d=c.data;if("/$"===d||"/&"===d)if(0===h)break;else h--;else"$"!==d&&"$?"!==d&&"$~"!==d&&"$!"!==d&&"&"!==d||h++}d=c.nextSibling;f.removeChild(c);c=d}while(c);for(;e.firstChild;)f.insertBefore(e.firstChild,c);g.data="$";g._reactRetry&&requestAnimationFrame(g._reactRetry)}}a.length=0};\n$RC=function(a,b){if(b=document.getElementById(b))(a=document.getElementById(a))?(a.previousSibling.data="$~",$RB.push(a,b),2===$RB.length&&("number"!==typeof $RT?requestAnimationFrame($RV.bind(null,$RB)):(a=performance.now(),setTimeout($RV.bind(null,$RB),2300>a&&2E3<a?2300-a:$RT+300-a)))):b.parentNode.removeChild(b)};';
export const completeBoundaryUpgradeToViewTransitions =
  '$RV=function(C,h){function k(a,c){var e=a.getAttribute(c);e&&(c=a.style,m.push(a,c.viewTransitionName,c.viewTransitionClass),"auto"!==e&&(c.viewTransitionClass=e),(a=a.getAttribute("vt-name"))||(a="_T_"+N++ +"_"),a=CSS.escape(a)!==a?"r-"+btoa(a).replace(/=/g,""):a,c.viewTransitionName=a,D=!0)}var D=!1,N=0,m=[];try{var f=document.__reactViewTransition;if(f){var d=$RV.bind(null,h);f.finished.then(d,d);return}var g=new Map;for(f=1;f<h.length;f+=2){var l=h[f].querySelectorAll("[vt-share]");for(d=0;d<l.length;d++){var b=l[d];g.set(b.getAttribute("vt-name"),b)}}var v=[];for(l=0;l<h.length;l+=2){var t=h[l],y=t.parentNode;if(y){var w=y.getBoundingClientRect();if(w.left||w.top||w.width||w.height){b=t;for(f=0;b;){if(8===b.nodeType){var u=b.data;if("/$"===u)if(0===f)break;else f--;else"$"!==u&&"$?"!==u&&"$~"!==u&&"$!"!==u||f++}else if(1===b.nodeType){d=b;var E=d.getAttribute("vt-name"),z=g.get(E);k(d,z?"vt-share":"vt-exit");z&&(k(z,"vt-share"),g.set(E,null));for(var F=d.querySelectorAll("[vt-share]"),\nA=0;A<F.length;A++){var G=F[A],H=G.getAttribute("vt-name"),I=g.get(H);I&&(k(G,"vt-share"),k(I,"vt-share"),g.set(H,null))}var J=d.querySelectorAll("[vt-parent-exit]");for(d=0;d<J.length;d++)k(J[d],"vt-parent-exit")}b=b.nextSibling}for(var K=h[l+1],n=K.firstElementChild;n;){null!==g.get(n.getAttribute("vt-name"))&&k(n,"vt-enter");var L=n.querySelectorAll("[vt-parent-enter]");for(b=0;b<L.length;b++)k(L[b],"vt-parent-enter");n=n.nextElementSibling}b=y;do for(var p=b.firstElementChild;p;){var M=p.getAttribute("vt-update");\nM&&"none"!==M&&!m.includes(p)&&k(p,"vt-update");p=p.nextElementSibling}while((b=b.parentNode)&&1===b.nodeType&&"none"!==b.getAttribute("vt-update"));v.push.apply(v,K.querySelectorAll(\'img[src]:not([loading="lazy"])\'))}}}if(D){var B=document.__reactViewTransition=document.startViewTransition({update:function(){C(h);for(var a=[document.documentElement.clientHeight,document.fonts.ready],c={},e=0;e<v.length;c={g:c.g},e++)if(c.g=v[e],!c.g.complete){var q=c.g.getBoundingClientRect();0<q.bottom&&0<q.right&&\nq.top<window.innerHeight&&q.left<window.innerWidth&&(q=new Promise(function(x){return function(r){x.g.addEventListener("load",r);x.g.addEventListener("error",r)}}(c)),a.push(q))}return Promise.race([Promise.all(a),new Promise(function(x){var r=performance.now();setTimeout(x,2300>r&&2E3<r?2300-r:500)})])},types:[]});g=function(){for(var a=m.length-3;0<=a;a-=3){var c=m[a],e=c.style;e.viewTransitionName=m[a+1];e.viewTransitionClass=m[a+1];""===c.getAttribute("style")&&c.removeAttribute("style")}};t=\nfunction(){document.__reactViewTransition===B&&(document.__reactViewTransition=null)};B.ready.then(g,g);B.finished.then(t,t);$RB=[];return}}catch(a){}C(h)}.bind(null,$RV);';
export const completeBoundaryWithStyles =
  '$RM=new Map;$RR=function(n,w,p){function u(q){this._p=null;q()}for(var r=new Map,t=document,h,b,e=t.querySelectorAll("link[data-precedence],style[data-precedence]"),v=[],k=0;b=e[k++];)"not all"===b.getAttribute("media")?v.push(b):("LINK"===b.tagName&&$RM.set(b.getAttribute("href"),b),r.set(b.dataset.precedence,h=b));e=0;b=[];var l,a;for(k=!0;;){if(k){var f=p[e++];if(!f){k=!1;e=0;continue}var c=!1,m=0;var d=f[m++];if(a=$RM.get(d)){var g=a._p;c=!0}else{a=t.createElement("link");a.href=d;a.rel=\n"stylesheet";for(a.dataset.precedence=l=f[m++];g=f[m++];)a.setAttribute(g,f[m++]);g=a._p=new Promise(function(q,x){a.onload=u.bind(a,q);a.onerror=u.bind(a,x)});$RM.set(d,a)}d=a.getAttribute("media");!g||d&&!matchMedia(d).matches||b.push(g);if(c)continue}else{a=v[e++];if(!a)break;l=a.getAttribute("data-precedence");a.removeAttribute("media")}c=r.get(l)||h;c===h&&(h=a);r.set(l,a);c?c.parentNode.insertBefore(a,c.nextSibling):(c=t.head,c.insertBefore(a,c.firstChild))}if(p=document.getElementById(n))p.previousSibling.data=\n"$~";Promise.all(b).then($RC.bind(null,n,w),$RX.bind(null,n,"CSS failed to load"))};';
export const completeSegment =
  '$RS=function(a,b){a=document.getElementById(a);b=document.getElementById(b);for(a.parentNode.removeChild(a);a.firstChild;)b.parentNode.insertBefore(a.firstChild,b);b.parentNode.removeChild(b)};';
export const formReplaying =
  'addEventListener("submit",function(a){if(!a.defaultPrevented){var b=a.target,d=a.submitter,c=b.action,e=d;if(d){var f=d.getAttribute("formAction");null!=f&&(c=f,e=null)}"javascript:throw new Error(\'React form unexpectedly submitted.\')"===c&&(a.preventDefault(),a=new FormData(b,e),c=b.ownerDocument||b,(c.$$reactFormReplay=c.$$reactFormReplay||[]).push(b,d,a))}});';
